# Generated by Django 4.2 on 2023-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="total_price",
            field=models.FloatField(default=0),
        ),
    ]
