# Generated by Django 4.2 on 2023-04-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.FloatField(default=0),
        ),
    ]
