# Generated by Django 4.2 on 2023-04-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_address_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="phone_number",
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
