# Generated by Django 4.2 on 2023-04-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_address_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="order.order",
            ),
        ),
    ]
